- .github/workflows/cmake-windows.yml
- include/Server.h
- src/Network/Server.cpp
- Correctly format WinSock errors with a message
This has lead to many(!) issues in the past, and makes
life harder for everyone doing support. This will display the
error code, together with an error message windows provides.
- Use SO_DONTLINGER to fix bind() address in use error
This will ensure the socket does not linger,
which fixes the common and *super* annoying issue of "bind(): address
already in use"
> Fix 10038, add more explanatory error messages

- src/Network/Core.cpp
This changes the serverlist request from:
POST https://backend.beammp.com/servers
to:
GET https://backend.beammp.com/servers-info
This is done in order to allow for more caching on the backend side, which will alleviate the load on the database and backend applications, and improve performance and reliability for users.
> Change serverlist request URL and Protocol

- src/Security/Login.cpp
Changed so the key file gets removed if the launcher gets an invalid response from the backend (usually a JS error and some html)  instead of a JSON while authenticating with the key file.
This should probably be fixed on the backend side.
> remove key if auth is unsuccessful

- src/Startup.cpp
* Update current BeamNG Version from 0.26.0 to 0.26.1
* Remove the warning and delay when mods are leftover from the previous session
* Update version number from 2.78 to 2.79
> Update BeamNG Version and remove Mod Delete warning & Delay

- src/Startup.cpp
The launcher complains if it can not delete a file when it's trying to clean the mods folder out. However the message it emits is unhelpful and does not offer a suggestion to what is going on.
This commit addresses this issue by telling the user what the launcher is trying to do and suggests checking if something is currently open in that directory. I figure not having to go into detail in *where* the folder is not necessary and (primarily) only happens if the user is inspecting the folder themselves and already knows where the folder is.
> Emit a useful message if cleaning the mods folder fails

- src/Network/Core.cpp
Adds the BeamMP patreon link to the list of urls that are allowed to be opened externally by the game
> Add BeamMP patreon to the allowed links

- README.md
- Do we need to mention that vcpkg should be installed in the first place?
- Do we need to specify what the difference between release and debug builds is?
- Are there any other prerequisites for building on windows?
---
> Add linux building instructions

- README.md
```
BeamMP-Launcher on  master via △ v3.30.5 
 ❯ sudo dnf group info "Development Tools" 
Dernière vérification de l’expiration des métadonnées effectuée il y a 0:48:01 le mer. 11 déc. 2024 08:39:18.
Groupe : Outils de développement
Description : Ces outils comprennent des outils de développement principaux comme git et cvs.
Paquets obligatoires :
gettext
Paquets par défaut :
diffstat
doxygen
git
patch
patchutils
subversion
systemtap
Paquets optionnels :
buildbot
colordiff
cvs
cvs2cl
cvsps
darcs
dejagnu
expect
gambas3-ide
git-annex
git-cola
git2cl
gitg
gtranslator
highlight
lcov
manedit
meld
monotone
myrepos
nemiver
qgit
quilt
rapidsvn
rcs
robodoc
scanmem
subunit
svn2cl
tig
tortoisehg
translate-toolkit
utrac
```
vcpkg isn't part of the Development Tools group on Fedora.
---
By creating …
> Add missing vcpkg package for Fedora

- src/Security/BeamNG.cpp
Beforehand, the launcher would check only if the game directory existed. This would lead to an error if the game was moved through Steam since Steam leaves the BeamNG.Drive directory behind. Now it checks for to see if integrity.json is inside. I also removed some commented out code I seem to have left behind when I was porting it.
I agree to this code (and the whole port to native Linux since the #63 was locked and I couldn't agree there) being licensed under AGPL 3.
> Update Check for Game Files on Native Linux

- src/Security/BeamNG.cpp
I couldn't launch the game without this.
---
> Fixed GameDir location issues.

- src/Network/Http.cpp
In some cases it can take longer than 10 seconds to connect to the backend, so in this PR I've raised the limit to 2 minutes.
---
> Up curl connection timeout to 2 minutes

- src/Network/Resources.cpp
This PR adds multiple features relating to mod downloads.
1. With this PR the launcher will convert old style mods (without hash) to new style mods (with hash). This is so people don't have to re-download all of their mods after joining a server which was previously on a version below 3.6.0
2. This PR will save the last used date of mods in a JSON file in the caching directory. This will allow for smart deletion of cached mods
---
> Mod download improvements

- src/Network/Core.cpp
- src/Network/GlobalHandler.cpp
- src/Network/Resources.cpp
- src/Network/VehicleEvent.cpp
Fixes the recv return value type. This PR corrects the recv return value type from `int32_t` to `int`. Casting the return value from `int` to `int32_t` (Currently the case, changed by this pr) would in some cases, if the transmitted packet was large enough, flip the value causing it to be a high negative number, which recv will never return. This happens frequently when downloading big mods over a fast connection.
---
> Fix recv return type and better download error handling

- src/GameStart.cpp
This PR logs the error `CreateProcessA` returns when failing on windows. This can help with figuring out why the launcher `Failed to Launch the game!`
---
> Get error code when the game fails to launch on windows

- src/Network/Resources.cpp
Launcher implementation for https://github.com/BeamMP/BeamMP-Server/pull/430. This PR checks if mods are protected, and if a mod is missing the launcher will notify the user about it and give them instructions on how to resolve it.
---
> Notify user about missing protected mods

- include/Options.h
- include/Utils.h
- src/GameStart.cpp
- src/Options.cpp
Simple addition to the CLI args. It could probably do with some validation, ie; making sure it ends in a slash.
cc: @WiserTixx
> Added CLI argument for `user-path`

- src/Network/Resources.cpp
This PR adds cached mods to the "Loading resources" pop-up in-game and makes it so that the count is actually right.
This PR also fixes the mod protection message because for some reason I forced it to be always off 😁.
---
> Show cached mods in download progress

- src/Startup.cpp
This PR makes it so that the launcher will first check for the presence of a .git folder before deleting the unpacked BeamMP directory.
This is useful when you're working on the BeamMP mod and you accidentally start the launcher without dev mode. (This has happened to me more times than I would like to admit.)
---
> Check if unpacked BeamMP has a .git folder before deleting it

- include/Network/network.hpp
- src/Config.cpp
- src/Network/Resources.cpp
Adds `DeleteDuplicateMods` option to the launcher config which, well, deletes mods with the same name if their hashes mismatch. Useful for development where client mod hashes can frequently change.
---
> Implement DeleteDuplicateMods option

- include/Http.h
- include/Utils.h
- src/Network/Http.cpp
- src/Network/Resources.cpp
- src/Startup.cpp
This PR makes the launcher update more reliable by downloading the update to a "new_BeamMP-Launcher.exe" file, instead of the launcher renaming itself to a backup (effectively bricking itself and the shortcut) and then hoping the download doesn't fail.
---
> Refine updating
